<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "univie_pure"
 *
 * Auto generated by Extension Builder 2016-01-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'u:cris',
	'description' => 'Query the pure research information system (as installed at the university of Vienna)',
	'category' => 'plugin',
	'author' => 'Christian Klettner',
	'author_email' => 'christian.klettner@univie.ac.at',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.6.16',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.1-7.7.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
